// The stock loader enters XIP at B000. Retain the SDK's symbolic RAM startup,
// using the factory entry sequence without the SDK's pre-ILM store.
#if defined(SV6X66_STOCK_CKW04)
__asm__(
".section .sv_stock_boot_hdr,\"ax\",@progbits\n"
".align 2\n"
".global SV6X66_StockEntryHeader\n"
"SV6X66_StockEntryHeader:\n"
"j SV6X66_StockEntry\n"
".section .sv_stock_boot,\"ax\",@progbits\n"
".global SV6X66_StockEntry\n"
"SV6X66_StockEntry:\n"
"sethi $gp, hi20(_SDA_BASE_)\n"
"ori $gp, $gp, lo12(_SDA_BASE_)\n"
"mfsr $r0, $msc_cfg\n"
"sethi $r1, 0x1000\n"
"and $r2, $r0, $r1\n"
"beqz $r2, 1f\n"
"sethi $r0, hi20(_ITB_BASE_)\n"
"ori $r0, $r0, lo12(_ITB_BASE_)\n"
"mtusr $r0, $itb\n"
"1:\n"
"sethi $sp, hi20(_stack)\n"
"ori $sp, $sp, lo12(_stack)\n"
"movi $r0, 0xf\n"
"mtsr $r0, $ilmb\n"
"sethi $r0, 0x100\n"
"ori $r0, $r0, 0x9\n"
"mtsr $r0, $dlmb\n"
"mfsr $r0, $mmu_ctl\n"
"ori $r0, $r0, 0x4\n"
"mtsr $r0, $mmu_ctl\n"
"mfsr $r0, $icm_cfg\n"
"mfsr $r1, $dcm_cfg\n"
"or $r0, $r0, $r1\n"
"andi $r0, $r0, 0x1c0\n"
"beqz $r0, 2f\n"
"mfsr $r0, $cache_ctl\n"
"movi $r1, -64\n"
"and $r0, $r0, $r1\n"
"movi $r1, 0x31\n"
"or $r0, $r0, $r1\n"
"mtsr $r0, $cache_ctl\n"
"2:\n"
"sethi $r15, hi20(_move_fast_boot_code)\n"
"ori $r15, $r15, lo12(_move_fast_boot_code)\n"
"jral $lp, $r15\n"
"sethi $r15, hi20(OS_Init_Nds32)\n"
"ori $r15, $r15, lo12(OS_Init_Nds32)\n"
"jr $r15\n"
".text\n"
);
#endif
