#if PLATFORM_TXW81X

#include "../../obk_config.h"
#include "../../new_common.h"
#include "../../new_cfg.h"
#include "../../logging/logging.h"
#include "../../httpserver/new_http.h"
#include "../hal_ota.h"
#include "lib/ota/fw.h"
#include "lib/ota/fwinfo.h"
#include "ef_cfg.h"

#define TXW81X_OTA_IO_CHUNK       1460
#define TXW81X_OTA_PROGRESS_STEP  (64 * 1024)

/*
 * Taixin's OTA helper rejects the unencrypted APP_compress.bin generated by
 * its own SDK. Accept only a header that the SDK parser recognizes as
 * unencrypted; encrypted images retain the vendor customer-ID check.
 */
extern int32 __real_fwinfo_check_customer_id(const uint8 *data);

int32 __wrap_fwinfo_check_customer_id(const uint8 *data)
{
	int32 err = 0;
	uint16 aes_enabled;

	if(data == NULL)
	{
		return -1;
	}

	aes_enabled = fwinfo_get_fw_aes_en(data, &err);
	if(err != 0)
	{
		return err;
	}

	if(aes_enabled == 0)
	{
		return 0;
	}

	return __real_fwinfo_check_customer_id(data);
}

static int TXW81X_OTA_GetStagingLimit(uint32 *start, uint32 *limit)
{
	struct ota_fwinfo info = { 0 };

	if(start == NULL || limit == NULL || ota_fwinfo_get(&info) != 0 ||
		info.flash1 == NULL || info.addr1 >= (uint32)EF_START_ADDR)
	{
		return -1;
	}

	*start = info.addr1;
	*limit = (uint32)EF_START_ADDR - info.addr1;
	return 0;
}

int http_rest_post_flash(http_request_t* request, int startaddr, int maxaddr)
{
	int total = 0;
	int towrite = 0;
	char* writebuf = request->bodystart;
	int buffered = request->bodylen;
	int ret = 0;
	int res = 0;
	int next_progress = TXW81X_OTA_PROGRESS_STEP;
	uint32 staging_start = 0;
	uint32 staging_limit = 0;

	(void)maxaddr;

	ADDLOG_INFO(LOG_FEATURE_OTA, "TXW81X OTA post len %d, initially buffered %d",
		request->contentLength, request->bodylen);

	if(request->contentLength <= 0)
	{
		ret = -1;
		ADDLOG_ERROR(LOG_FEATURE_OTA, "Content-length is 0");
		goto update_ota_exit;
	}

	if(TXW81X_OTA_GetStagingLimit(&staging_start, &staging_limit) != 0)
	{
		ret = -1;
		ADDLOG_ERROR(LOG_FEATURE_OTA, "TXW81X OTA: invalid staging geometry");
		goto update_ota_exit;
	}

	if(startaddr < 0 || (uint32)startaddr > staging_limit ||
		(uint32)request->contentLength > staging_limit - (uint32)startaddr)
	{
		ret = -1;
		ADDLOG_ERROR(LOG_FEATURE_OTA,
			"TXW81X OTA image is too large: %d bytes at offset %d, maximum %u bytes",
			request->contentLength, startaddr, staging_limit);
		goto update_ota_exit;
	}

	ADDLOG_INFO(LOG_FEATURE_OTA,
		"TXW81X OTA staging range: 0x%08x-0x%08x (%u bytes)",
		staging_start, staging_start + staging_limit, staging_limit);

	towrite = request->contentLength;
	if(buffered < 0)
	{
		buffered = 0;
	}
	else if(buffered > towrite)
	{
		buffered = towrite;
	}

	while(towrite > 0)
	{
		int writelen;

		if(buffered <= 0)
		{
			int recvmax = request->receivedLenmax;

			if(recvmax <= 0 || recvmax > TXW81X_OTA_IO_CHUNK)
			{
				recvmax = TXW81X_OTA_IO_CHUNK;
			}
			if(recvmax > towrite)
			{
				recvmax = towrite;
			}

			writebuf = request->received;
			buffered = recv(request->fd, writebuf, recvmax, 0);
			if(buffered <= 0)
			{
				ADDLOG_ERROR(LOG_FEATURE_OTA,
					"recv returned %d - remaining %d of %d bytes",
					buffered, towrite, request->contentLength);
				ret = -1;
				goto update_ota_exit;
			}
		}

		writelen = buffered;
		if(writelen > TXW81X_OTA_IO_CHUNK)
		{
			writelen = TXW81X_OTA_IO_CHUNK;
		}
		if(writelen > towrite)
		{
			writelen = towrite;
		}

		/* Sector erase is required because the final 64 KiB block of the
		 * second slot overlaps EasyFlash at EF_START_ADDR. */
		res = libotaV2_write_fw(request->contentLength,
			0, 1, 0, (uint32)startaddr,
			(uint8*)writebuf, (uint16)writelen);
		if(res != 0)
		{
			ADDLOG_ERROR(LOG_FEATURE_OTA,
				"libotaV2_write_fw failed at offset %d, len %d, res %d",
				startaddr, writelen, res);
			ret = -1;
			goto update_ota_exit;
		}

		total += writelen;
		startaddr += writelen;
		towrite -= writelen;
		writebuf += writelen;
		buffered -= writelen;

		if(total >= next_progress || towrite == 0)
		{
			ADDLOG_INFO(LOG_FEATURE_OTA,
				"TXW81X OTA progress: %d/%d bytes",
				total, request->contentLength);
			while(next_progress <= total)
			{
				next_progress += TXW81X_OTA_PROGRESS_STEP;
			}
		}

		rtos_delay_milliseconds(10);
	}

update_ota_exit:
	if(ret != -1)
	{
		ADDLOG_INFO(LOG_FEATURE_OTA, "OTA is successful: %d bytes written", total);
	}
	else
	{
		ADDLOG_ERROR(LOG_FEATURE_OTA, "OTA failed after %d of %d bytes",
			total, request->contentLength);
		return http_rest_error(request, ret, "error");
	}

	http_setup(request, httpMimeTypeJson);
	hprintf255(request, "{\"size\":%d}", total);
	poststr(request, NULL);
	CFG_IncrementOTACount();
	return 0;
}

#endif
