#if PLATFORM_TXW81X

#include "../../obk_config.h"
#include "../../new_common.h"
#include "../../new_cfg.h"
#include "../../logging/logging.h"
#include "../../httpserver/new_http.h"
#include "../hal_ota.h"
#include "lib/ota/fw.h"
#include "lib/ota/fwinfo.h"

/*
 * The TXW81X SDK OTA API takes a uint16 length. Keep every write small even
 * when the HTTP server has already buffered a large part of the request body.
 * The vendor TCP updater also feeds libota_write_fw() in 1460-byte pieces.
 */
#define TXW81X_OTA_IO_CHUNK       1460
#define TXW81X_OTA_PROGRESS_STEP  (64 * 1024)

/*
 * The precompiled Taixin OTA library calls fwinfo_check_customer_id() before
 * it opens or erases flash. The APP_compress.bin generated by this SDK is
 * deliberately unencrypted (project/makecode.ini has AesEnable=0), but that
 * library function returns -1 for a valid unencrypted image.
 *
 * platforms/TXW81X/OpenBeken.mk links with:
 *     -Wl,--wrap=fwinfo_check_customer_id
 *
 * This wrapper accepts only a structurally valid unencrypted TXW81X image.
 * Encrypted images still go through the original SDK customer-ID check.
 */
extern int32 __real_fwinfo_check_customer_id(const uint8 *data);

int32 __wrap_fwinfo_check_customer_id(const uint8 *data)
{
	int32 err = 0;
	uint16 aes_enabled;

	if(data == NULL)
	{
		ADDLOG_ERROR(LOG_FEATURE_OTA,
			"TXW81X OTA: customer-ID check received a null header");
		return -1;
	}

	/* fwinfo_get_fw_aes_en() first validates the complete firmware header. */
	aes_enabled = fwinfo_get_fw_aes_en(data, &err);
	if(err != 0)
	{
		ADDLOG_ERROR(LOG_FEATURE_OTA,
			"TXW81X OTA: invalid firmware header, fwinfo error %d", err);
		return err;
	}

	if(aes_enabled == 0)
	{
		ADDLOG_INFO(LOG_FEATURE_OTA,
			"TXW81X OTA: valid unencrypted image; bypassing SDK customer-ID rejection");
		return 0;
	}

	/* Preserve the vendor security check for genuinely encrypted images. */
	return __real_fwinfo_check_customer_id(data);
}

int http_rest_post_flash(http_request_t* request, int startaddr, int maxaddr)
{
	int total = 0;
	int towrite = 0;
	char* writebuf = request->bodystart;
	int buffered = request->bodylen;
	int ret = 0;
	int res = 0;
	int next_progress = TXW81X_OTA_PROGRESS_STEP;

	(void)maxaddr;

	ADDLOG_INFO(LOG_FEATURE_OTA, "TXW81X OTA post len %d, initially buffered %d",
		request->contentLength, request->bodylen);

	if(request->contentLength <= 0)
	{
		ret = -1;
		ADDLOG_ERROR(LOG_FEATURE_OTA, "Content-length is 0");
		goto update_ota_exit;
	}

	towrite = request->contentLength;

	/* Do not consume beyond the declared HTTP request body. */
	if(buffered < 0)
	{
		buffered = 0;
	}
	else if(buffered > towrite)
	{
		buffered = towrite;
	}

	while(towrite > 0)
	{
		int writelen;

		/* Once the bytes already held after the HTTP headers are exhausted,
		 * continue streaming the body from the same socket. */
		if(buffered <= 0)
		{
			int recvmax = request->receivedLenmax;

			if(recvmax <= 0 || recvmax > TXW81X_OTA_IO_CHUNK)
			{
				recvmax = TXW81X_OTA_IO_CHUNK;
			}
			if(recvmax > towrite)
			{
				recvmax = towrite;
			}

			writebuf = request->received;
			buffered = recv(request->fd, writebuf, recvmax, 0);
			if(buffered <= 0)
			{
				ADDLOG_ERROR(LOG_FEATURE_OTA,
					"recv returned %d - remaining %d of %d bytes",
					buffered, towrite, request->contentLength);
				ret = -1;
				goto update_ota_exit;
			}
		}

		writelen = buffered;
		if(writelen > TXW81X_OTA_IO_CHUNK)
		{
			writelen = TXW81X_OTA_IO_CHUNK;
		}
		if(writelen > towrite)
		{
			writelen = towrite;
		}

		res = libota_write_fw(request->contentLength, startaddr,
			(uint8*)writebuf, (uint16)writelen);

		/* The vendor updater treats zero as success and any non-zero value
		 * as failure. Do not accept -1: that previously produced a fake
		 * successful upload while writing nothing to flash. */
		if(res != 0)
		{
			ADDLOG_ERROR(LOG_FEATURE_OTA,
				"libota_write_fw failed at offset %d, len %d, res %d",
				startaddr, writelen, res);
			ret = -1;
			goto update_ota_exit;
		}

		total += writelen;
		startaddr += writelen;
		towrite -= writelen;
		writebuf += writelen;
		buffered -= writelen;

		if(total >= next_progress || towrite == 0)
		{
			ADDLOG_INFO(LOG_FEATURE_OTA,
				"TXW81X OTA progress: %d/%d bytes",
				total, request->contentLength);
			while(next_progress <= total)
			{
				next_progress += TXW81X_OTA_PROGRESS_STEP;
			}
		}

		rtos_delay_milliseconds(10);
	}

update_ota_exit:
	if(ret != -1)
	{
		ADDLOG_INFO(LOG_FEATURE_OTA, "OTA is successful: %d bytes written", total);
	}
	else
	{
		ADDLOG_ERROR(LOG_FEATURE_OTA, "OTA failed after %d of %d bytes",
			total, request->contentLength);
		return http_rest_error(request, ret, "error");
	}

	http_setup(request, httpMimeTypeJson);
	hprintf255(request, "{\"size\":%d}", total);
	poststr(request, NULL);
	CFG_IncrementOTACount();
	return 0;
}

#endif
